### ISSUE TITLE
Greek Translation

### ISSUE THREAD

**Issue by Idrinth** [IDotD/Translations#2]

**Comment by Theodotosp** [comment]
i have some "issues" with the translations! There are some areas that work and others that don't. I will post screenshots so that you can find out the solution.

![image](https://cloud.githubusercontent.com/assets/22475199/21899838/707ff40a-d8fa-11e6-8fba-07317e62e294.png)
In this photo everything works but the top tabs.

![image](https://cloud.githubusercontent.com/assets/22475199/21899930/bb1f6b08-d8fa-11e6-9b23-2e5a547dc1f6.png)
In the section tab only the last line is translated.

![image](https://cloud.githubusercontent.com/assets/22475199/21899975/e09bbe22-d8fa-11e6-80a3-a200c0ee4d80.png)
In the tiers tab the boss' name and race isnt translated

![image](https://cloud.githubusercontent.com/assets/22475199/21900058/168aa246-d8fb-11e6-9b5a-649ea9b700bf.png)
In land tab not everything is translated.

For now I have seen these "issues".

**Comment by Ardenian** [comment]
As for the Land tab, there isn't translation in-game, right ? I excluded them therefore when I collected the texts, so they match the in-game content. What's your opinion on this one, @Idrinth ?

The Settings tab should be supported, will have a look.

**Comment by Idrinth** [comment]
I'd vote for having the option of changing those name, but I also agree it might be helpful to have the original there as well.

land.pub = Gasthaus(Pub)

for example

**Comment by Ardenian** [comment]
@Idrinth Did you fix some of the issues Theo mentioned ? Setting and Tiers tab show the correct language for me. Only Land tab and popup seem to be missing, as well as group names

**Comment by Idrinth** [comment]
@Ardenian I didn't check if there might be a typo somewhere in the greek version, didn't do anything in regards eithe ticket yet

**Comment by Ardenian** [comment]
Land tab land names and tab names are covered in en.json and de.json now, but I need your help with adding them in the code, @Idrinth my solution does not work, though it should after my scope

**Comment by Idrinth** [comment]
honestly, what the hell did you do to those files? every line or nearly every line changed in four languages? @Ardenian

**Comment by Idrinth** [comment]
ok, fixed the invalid json, fixed the formatting. Please test before changing stuff in a master branch, you just broke all the translated fields for every single language.
